#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/mirvdesk/mirvdesk /usr/bin/mirvdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/mirvdesk.service ]; then
			rm /etc/systemd/system/mirvdesk.service /usr/lib/systemd/system/mirvdesk.service /usr/lib/systemd/user/mirvdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/mirvdesk/files/systemd/mirvdesk.service /usr/lib/systemd/system/mirvdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload mirvdesk.service: Unit mirvdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/mirvdesk.service:10: Executable path is not absolute: pkill -f "mirvdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/mirvdesk.service
		fi
		systemctl daemon-reload
		systemctl enable mirvdesk
		systemctl start mirvdesk
	fi
fi
